### ISSUE TITLE
Error occurred

### ISSUE THREAD

**Issue by qhdwns123** [Tarsnap/kivaloo#34]
Hi.

An error occurs

COMMAND: sudo ../../kvlds/kvlds -s stor/sock_kvlds -l stor/sock_lbs

ERROR: kvlds: Address must contain port number: stor/sock_kvlds
kvlds: Error resolving socket address: stor/sock_kvlds

**Comment by cperciva** [comment]
When specifying unix sockets, you need to provide an absolute path.  The leading '/' is how it distinguishes between unix socket addresses and TCP/IP socket addresses.

**Comment by qhdwns123** [comment]
Okay, Thanks!
